services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - oauth2-proxy
    volumes:
      - ./nginx/html:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - keycloak_net

  oauth2-proxy:
    container_name: oauth2-proxy
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
    environment:
      OAUTH2_PROXY_PROVIDER: keycloak-oidc
      OAUTH2_PROXY_CLIENT_ID: ${OAUTH2_PROXY_CLIENT_ID}
      OAUTH2_PROXY_CLIENT_SECRET: ${OAUTH2_PROXY_CLIENT_SECRET}
      OAUTH2_PROXY_COOKIE_SECURE: "false"
      OAUTH2_PROXY_COOKIE_SECRET: ${OAUTH2_PROXY_COOKIE_SECRET}
      OAUTH2_PROXY_OIDC_ISSUER_URL: http://${PUBLIC_IP}:8080/realms/master
      OAUTH2_PROXY_REDIRECT_URL: http://${PUBLIC_IP}/oauth2/callback
      OAUTH2_PROXY_EMAIL_DOMAINS: "*"
      OAUTH2_PROXY_EMAIL_VERIFIED: "false"
      OAUTH2_PROXY_INSECURE_OIDC_ALLOW_UNVERIFIED_EMAIL: "true"
      OAUTH2_PROXY_OIDC_EMAIL_CLAIM: "sub"
      OAUTH2_PROXY_UPSTREAMS: http://nginx
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: "true"
      OAUTH2_PROXY_HTTP_ADDRESS: "0.0.0.0:4180"
      OAUTH2_PROXY_SESSION_STORAGE_TYPE: redis
      OAUTH2_PROXY_REDIS_CONNECTION_URL: redis://redis:6379/0
      OAUTH2_PROXY_SET_XAUTHREQUEST: "true"
      OAUTH2_PROXY_PASS_ACCESS_TOKEN: "true"
      OAUTH2_PROXY_SSL_INSECURE_SKIP_VERIFY: "true" # For HTTP
      OAUTH2_PROXY_COOKIE_DOMAIN: "${PUBLIC_IP}"
      OAUTH2_PROXY_SKIP_JWT_BEARER_TOKENS: "true"
    ports:
      - "4180:4180"
    networks:
      - keycloak_net

  redis:
    container_name: redis
    image: redis:7-alpine
    networks:
      - keycloak_net

volumes:
  pgdata:
  
networks:
  keycloak_net:
    driver: bridge