---
- name: Tear down Docker Compose stack and uninstall Docker
  hosts: all
  become: true

  tasks:
    - name: Stop and remove NGINX stack
      community.docker.docker_compose_v2:
        project_src: "/tmp/docker/"
        files:
          - docker-compose-nginx.yaml
        remove_volumes: true
        state: absent

    - name: Stop and remove Keycloak stack
      community.docker.docker_compose_v2:
        project_src: "/tmp/docker/"
        files:
          - docker-compose-keycloak.yaml
        remove_volumes: true
        state: absent